### ISSUE TITLE
Fails silently for (some) old node versions - include min version in ReadMe?

### ISSUE THREAD

**Issue by ICornwell** [raml-org/ramldt2jsonschema#102]
When running CLI or from .js code, if the node version is old (I was running on 6.11.0) dt2js exits with no errors or warnings. (failure comes from node's child_process.js). I don't think this is a fault with the project, but if the ReadMe included in minimum node version, it would be nice.

**Comment by jstoiko** [comment]
v6 is deprecated. See [Node JS release schedule](https://nodejs.org/en/about/releases/) for more information on this.
