### ISSUE TITLE
Add type:nil support

### ISSUE THREAD

**Issue by postatum** [raml-org/ramldt2jsonschema#104]
See https://github.com/raml-org/ramldt2jsonschema/pull/96#discussion_r320992010 and https://github.com/aml-org/amf/issues/555

**Comment by jstoiko** [comment]
@postatum: AMF 3.5.1 which was just released addresses this issue

**Comment by postatum** [comment]
Will be resolved in a new version by https://github.com/raml-org/ramldt2jsonschema/commit/e3be4cd35be6955479b5efdf6bb39a7404e55eeb
