### ISSUE TITLE
`dt2js` does not always output a `$schema` property

### ISSUE THREAD

**Issue by jstoiko** [raml-org/ramldt2jsonschema#106]
```
$ dt2js --draft=04 test/integration/raml/person_type_include.raml Person

$ dt2js --draft=06 test/integration/raml/person_type_include.raml Person | jq '.["$schema"]'

$ dt2js --draft=07 test/integration/raml/person_type_include.raml Person | jq '.["$schema"]'
"http://json-schema.org/draft-07/schema#"
```

Not sure if this is something specific to certain types because other types work as expected with all 3 draft versions, see:
```
$ dt2js --draft=04 test/integration/raml/complex_cat.raml Cat | jq '.["$schema"]'
"http://json-schema.org/draft-04/schema#"
$ dt2js --draft=06 test/integration/raml/complex_cat.raml Cat | jq '.["$schema"]'
"http://json-schema.org/draft-06/schema#"
$ dt2js --draft=07 test/integration/raml/complex_cat.raml Cat | jq '.["$schema"]'
"http://json-schema.org/draft-07/schema#"
```

**Comment by postatum** [comment]
In case of `test/integration/raml/person_type_include.raml`, type `Person` is defined as `type: !include ../json/simple_person.json` which doesn't specify `$schema` property.

I guess when running `toJsonShema`, types like that are completely replaced by a json schema they include. I've also just noticed that output schema doesn't include `Person.description`.

**Comment by jstoiko** [comment]
by "manually", I'm assuming you mean "ramldt2jsonschema", right?

**Comment by postatum** [comment]
> by "manually", I'm assuming you mean "ramldt2jsonschema", right?

Yes. We would add draft-04 `$schema` if it's missing and then process schema as usual.

**Comment by postatum** [comment]
This issue can be fixed as this comment suggests: https://github.com/aml-org/amf/issues/557#issuecomment-536688740
