### ISSUE TITLE
Define what versions of RAML and JSON Schema are in use

### ISSUE THREAD

**Issue by Relequestual** [raml-org/ramldt2jsonschema#11]
Looking at the readme.md, I don't know which versions of RAML or JSON Schema the library supports.

**Comment by jstoiko** [comment]
Thanks for the suggestion! It supports RAML 1.0 - as data types were introduced in that version - and JSON Schema draft 4. I agree we should add this to the docs so it's clear.

**Comment by sharkberto** [comment]
how should the field argument for RAML Data type be structured? Does it represent the RAML data type to convert from? Do I specify 0.8 to convert to 1.0, or do I specify 1.0?

**Comment by jstoiko** [comment]
@sharkberto: I think you're confusing`ramldt2jsonschema` with something else. `ramldt2jsonschema` is for converting RAML data types to JSON schema and vice-versa. RAML data type is a feature of RAML 1.0, not 0.8.

**Comment by jstoiko** [comment]
Added mention in README: RAML 1.0 + JSON Schema Draft 4 (Draft 6 coming soon). Closing.
