### ISSUE TITLE
Question js2dt

### ISSUE THREAD

**Issue by karolbmx** [raml-org/ramldt2jsonschema#113]
Hi,

one quick question - i want to transform JSON schema to DT:
complex_cat.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "A representation of an event",
    "properties": {
        "category": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "dtend": {
            "description": "Event ending time",
            "format": "date-time",
            "type": "string"
        },
        "dtstart": {
            "description": "Event starting time",
            "format": "date-time",
            "type": "string"
        },
        "duration": {
            "description": "Event duration",
            "format": "time",
            "type": "string"
        },
        "location": {
            "type": "string"
        },
        "rdate": {
            "description": "Recurrence date",
            "format": "date-time",
            "type": "string"
        },
        "rrule": {
            "description": "Recurrence rule",
            "type": "string"
        },
        "summary": {
            "type": "string"
        },
        "url": {
            "format": "uri",
            "type": "string"
        }
    },
    "required": [
        "dtstart",
        "summary"
    ],
    "type": "object"
}

command: **js2dt C:\test\complex_cat.json Test**
result:
amf.core.exception.UnsupportedVendorException: Cannot parse document with specified vendor: OAS 2.0

Why im getting this error ?

**Comment by postatum** [comment]
Hi @karolbmx. Please wrap the json you provided matches the one you tried to convert, because it works for me on Ubuntu

**Comment by karolbmx** [comment]
It's works when file is under npm folder in example this command will works:
C:\Users\karol\AppData\Roaming\npm\js2dt complex_cat.json test
but this will throw exception:
C:\Users\karol\AppData\Roaming\npm\js2dt C:\Users\karol\AppData\Roaming\npm\complex_cat.json test

Any idea why?
Its possible to provide json schema as String instead path to file?
Thanks

**Comment by postatum** [comment]
@karolbmx you could install the lib as a local npm dependency and use it from your nodejs code: https://github.com/raml-org/ramldt2jsonschema#js2dt-1

Meanwhile, please:
1. Try to run (note forward slashes) ` C:\Users\karol\AppData\Roaming\npm\js2dt C:/Users/karol/AppData/Roaming/npm/complex_cat.json test` and let me know how it works.
2. Let me know what nodejs version you use.

**Comment by postatum** [comment]
@karolbmx Hi. Did you resolve this issue?

**Comment by karolbmx** [comment]
Node v10.16.3. I have prepared workaround (copy to root/parse/remove).
Thanks

**Comment by postatum** [comment]
> Node v10.16.3. I have prepared workaround (copy to root/parse/remove).
> Thanks

Ok, nice.

Did this work for you?:

> 1. Try to run (note forward slashes) ` C:\Users\karol\AppData\Roaming\npm\js2dt C:/Users/karol/AppData/Roaming/npm/complex_cat.json test` and let me know how it works.

**Comment by postatum** [comment]
Closing as there was no answer for a long time. Feel free to reopen.
