### ISSUE TITLE
Is a 'full API definition json' to raml conversion possible?

### ISSUE THREAD

**Issue by OzBob** [raml-org/ramldt2jsonschema#115]
I have a large API definition with all the types and protocols and traits etc. in one file formatted as json. Any suggestions on how to convert it into RAML?

**Comment by postatum** [comment]
Hi @OzBob.
Depends on what you mean by `full API definition json`.

If your API is expressed in terms of RAML but is represented as JSON, you should use some library that converts json to yaml.

If your API is is expressed as OAS 2.0, then you should use a library which powers this one: [webapi-parser](https://github.com/raml-org/webapi-parser). The code you need would look like:
```js
const wap = require('webapi-parser').WebApiParser

async function main() {
  const myApi = '' // string or file path
  let model = await wap.oas20.parse(myApi)
  model = await wap.oas20.resolve(model) // optional if your API definition does not reference another files
  const ramlString = await wap.raml10.generateString(model)
}

main()
```

**Comment by postatum** [comment]
E.g. in the first option you can achieve what you need with [js-yaml](https://github.com/nodeca/js-yaml) like so:

```js
const yaml = require('js-yaml')

const myApi = '{"foo": 1}'
const apiObj = JSON.parse(myApi)
const yamlString = yaml.dump(apiObj)
```

**Comment by postatum** [comment]
Hi @OzBob. Did my comments help? If so, please close this issue.

**Comment by OzBob** [comment]
First option was spot on. I had to remove the 'uses' node from the source json, but that's ok.

**Comment by OzBob** [comment]
@postatum I tried using the yaml produced but it's not valid raml, it's array for types representation has '-' prefixes everywhere.

types:
  addDocumentToFolderRequest:
    type: object
    properties:
      - type: string
        name: document_id
        displayName: document_id
        typePropertyKind: TYPE_EXPRESSION
        required: true
        description: "Unique ID of the document\_assigned by iManage Work Server."
        key: document_id
where as the raml spec https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#type-expressions says name on new line with type on a new line indented: 
types:
  Phone:
    type: object
    properties:
      manufacturer:
        type: string
      numberOfSIMCards:
        type: number
is expected.

**Comment by OzBob** [comment]
Is there a JSON to RAML: version of this tool? https://github.com/raml-org/raml-js-parser-2/

**Comment by postatum** [comment]
@OzBob can you provide an example of RAML for which you get an array in `properties:`?

**Comment by OzBob** [comment]
This node code:

```
'use strict'
const yaml = require('js-yaml')
const join = require('path').join
const fs = require('fs')
async function main() {
  const jsonData = fs.readFileSync('./imanageFormattedNoUses.json').toString()
  const apiObj = JSON.parse(jsonData)
  const library = '#%RAML 1.0\n' + yaml.safeDump(apiObj, { 'noRefs': true })
  fs.writeFileSync('imanageFormattedNoUses.yaml', library)
  console.log(library)
}
main()
```

Produces: 
```
"types": {
...	"categoryOperations": {
		"type": "object",
		"properties": [
			{
				"type": "boolean",
				"name": "add_categories",
				"displayName": "add_categories",
				"typePropertyKind": "TYPE_EXPRESSION",
				"required": true,
				"description": "Provides an option to the user to create a new category.",
				"key": "add_categories"
				},
			{
				"type": "boolean",
				"name": "add_shortcuts",
				"displayName": "add_shortcuts",
				"typePropertyKind": "TYPE_EXPRESSION",
				"required": true,
				"description": "Adds shortcuts to other objects to a category.",
				"key": "add_shortcuts"
			},
...
```

'js-yaml' conversion is a faithful representation of the array of 'properties' array, just not valid RAML.

I can give you a copy of the fill API doc, but it's private so maybe via email ...

**Comment by postatum** [comment]
Thanks @OzBob. I believe you've already noticed that the JSON data you try to convert has `properties` value as an array as well. I thinkg you should either restructure it in code "by hand" or make sure whatever produces that JSON data outputs `properties` as an object instead of an array.

**Comment by OzBob** [comment]
thanks @postatum will do some hand coding

This https://github.com/raml-org/raml-js-parser-2/  does RAML to JSON. 

Is there a JSON to RAML app/pkg?

**Comment by postatum** [comment]
> Is there a JSON to RAML app/pkg?

Approach with `js-yaml` should do what you need if you use `raml-1-parser` to convert RAML to JSON, because `raml-1-parser` produces `properties` as an object instead of an array.

**Comment by OzBob** [comment]
@postatum thank you for the advice and assistance. 
All the various combinations of converters couldn't convert my JSON property arrays into RAML property objects. 
```js-yaml.safeDump``` dropped 'properties' that weren't objects.
I will request the original vendor supply a more compatibly file.
