### ISSUE TITLE
All versions greater than v1.0.0 have CLI dt2js broken!

### ISSUE THREAD

**Issue by StatusCode404** [raml-org/ramldt2jsonschema#128]
All versions greater than v1.0.0 have CLI dt2js broken!
Last working version is ramldt2jsonschema@1.0.0
Using node version 16.0.0
OS:	Mac OS X
OS ver:	10.15.7

running a command like
`$ dt2js ./cdm-library.raml Address --validate`
fails on all versions greater than 1.0.0

The library file contains Types which are referenced using "!include" which are in individual files per type in a subfolder.

This breaks some of our automation if we reference the latest builds.
Our current workaround is to use v1.0.0 using:
`$ npm install -g ramldt2jsonschema@1.0.0`

**Comment by StatusCode404** [comment]
Please fix the regression so we can utilise the latest version.

**Comment by AstroBurrito** [comment]
Have gotten it to work with dt2js version >1.0.0.  "ajv" nodeJS module prerequisite was missing.  Perhaps the documentation should be updated clearly indicating this requirement.  I only figured it out looking at the tag notes.

**Comment by StatusCode404** [comment]
@AstroBurrito's solution worked.
