### ISSUE TITLE
Some improvements (part 2)

### ISSUE THREAD

**Issue by jstoiko** [raml-org/ramldt2jsonschema#18]
**JSON Schema->RAML DT:**
- [x] make output less verbose
  - remove `required: true` (RAML defaults to true)
  - replace `required: false` by `<property>?` [1]
  - for properties that only have a `{"type" : <type>}` defined in JSON schema, write it in the form `<propertyName>: <type>` in RAML

**RAML DT->JSON Schema:**
- [x] convert RAML pattern properties  ([here](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#additional-properties) search for `This pattern property`) to JSON `object.patternProperties`
- [x] support for external includes

--
[1] see [RAML 1.0 Property Declaration](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#property-declarations)

**Comment by brevity** [comment]
For the second item, 'type string with media wasn't necessarily a RAML type file before'. 

What sort of state in the JSON Schema are we trying to account for. Currently, js2dt() identifies a file if `data.type` is a string, and  `data.media.binaryEncoding = 'binary'` Is this issue raised when converting from raml->js and back again?
