### ISSUE TITLE
RAML DT > JSON schema

### ISSUE THREAD

**Issue by jstoiko** [raml-org/ramldt2jsonschema#2]
- [x] create a `dt2js` CLI that accepts params and outputs result of `datatype-expansion`
- [x] write output of `dt2js` to a schema.json file
- [x] make it possible to use this tool from JS code
- [x] when used from JS code, result should be returned from function, NOT written to file
- [x] build a very complex RAML data type that contains ALL features and use that to verify what needs to be changed
- [x] collect JSON schema validation errors
- [x] test JSON schema against a few other validators
- [x] write code to turn scripts output into valid JSON schema
- [x] add support for `fileTypes`

**Comment by sichvoge** [comment]
is this already fully supported or do we still have to figure our how to support `fileTypes`? i think we already came to a conclusion right? can you quickly update this ticket @jstoiko

**Comment by jstoiko** [comment]
yes, so unless anyone has any objections, I think this makes the most sense:
```
Image:
    type: file
    fileType: ['image/jpeg', 'image/png']
```
should become:
```
{
    "type": "string",
    "media": {
        "binaryEncoding": "base64",
        "anyOf": [
            { "mediaType": "image/jpeg" },
            { "mediaType": "image/png" }
        ]
    }
}
```

**Comment by sichvoge** [comment]
What are the implications using that format vs a different option?

**Comment by sichvoge** [comment]
We should also create some documentation that outlines the mapping if there is something different to the JSON spec vs RAML data types.

**Comment by postatum** [comment]
@sichvoge 
> What are the implications using that format vs a different option?

If you mean using `fileTypes` vs `media.anyOf`: if we leave `fileTypes` as is and someone will want to use them for validation in JSON, they won't be able to, because `fileTypes` is not a standard JSON Schema keyword.

**Comment by sichvoge** [comment]
OK, make sense. Let's stick with the `anyOf` then.
