### ISSUE TITLE
js2dt: Invalid conversion of "additionalProperties"

### ISSUE THREAD

**Issue by dploeger** [raml-org/ramldt2jsonschema#21]
There's a difference about the "additionalProperties" facet in jsonschema and the RAML specification.

In Jschonschema it's either a boolean or a JSON schema (or a reference), that additional properties must obey.

In the RAML specification, it's only a boolean. The type of additional properties has to be specified as:

```raml
#%RAML 1.0
title: My API With Types
types:
  Person:
    properties:
      name:
        required: true
        type: string
      age:
        required: false
        type: number
      //: # force all additional properties to be a string
        type: string
```

So, in this example:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "Test": {
      "description": "test",
      "type": "object",
      "properties": {
        "test": {
          "description": "test.test",
          "type": "object",
          "title": "test",
          "additionalProperties": {}
        }
      }
    }
  }
}
```

if the included additionalProperties-facet is...

* of type boolean: just copy it to the RAML output
* empty object: set additionalProperties to "true" in the RAML output
* a reference: set additionalProperties to "false" in the RAML output and add a new property like this:

```raml
(...)
properties:
  //:
    type: <referenced type from json>
(..)
```

**Comment by jstoiko** [comment]
@dploeger: thanks for submitting this issue. would you mind taking a look at #28 to make sure it's what you expected?

**Comment by dploeger** [comment]
That one looks really nice, yes. Thanks.
