### ISSUE TITLE
support JSON schema draft-6

### ISSUE THREAD

**Issue by jstoiko** [raml-org/ramldt2jsonschema#22]
- [x] js2dt 
  - [x] support for draft 4
  - [x] support for draft 6
- [x] dt2js
  - [x] support for draft 4
  - [x] support for draft 6

See: 
- http://json-schema.org/draft-06/json-schema-migration-faq.html

**Comment by jstoiko** [comment]
@Relequestual: anything else we should look at?

**Comment by Relequestual** [comment]
@jstoiko I don't think so. Not even read the guide myself.
@handrews ?

**Comment by handrews** [comment]
@jstoiko I published draft-7 on Monday so you're out of date ;-)
But that document is all you should look at for draft-6.  I'll be adding the draft-7 migration notes in the next few days.  Moving from 6 to 7 is simpler: all valid draft-06 schemas are also valid draft-07 schemas.  Draft-07 just adds a few things.

**Comment by jstoiko** [comment]
fyi, there is a PR in the works here: https://github.com/raml-org/ramldt2jsonschema/pull/33

**Comment by jstoiko** [comment]
(updated description with current progress)

We are assessing whether or not there is any interest in outputting JSON Schema draft-07 instead of draft-06 from RAML type definitions. We're also thinking of making `dt2js` have an option for providing a draft but it would require more thoughts/work so before going forward, we want to make sure that's what people really need.

If any of you (CC: @kace91) have an opinion, please speak up!

**Comment by handrews** [comment]
@jstoiko note that all draft-06 schemas are also valid draft-07 schemas, so I think it's mostly useful to think about where and how people will use the output.

**Comment by jstoiko** [comment]
right. I am fine with sticking to draft6, especially knowing that it’s forward compatible.

I guess what I am asking is if there is a valid use case for exporting RAML to draft7 in that, are there new features in draft7 that can be better expressed and translated from RAML (and that people would feel would be beneficial to them).

**Comment by handrews** [comment]
@jstoiko the only major new validation features in draft-07 are `if`/`then`/`else` and several new values for `format`.  draft-07 was mostly about hyper-schema.

**Comment by jstoiko** [comment]
thanks @handrews, tracking this here now: https://github.com/raml-org/ramldt2jsonschema/issues/54
