### ISSUE TITLE
Error by conversion more RAML files to one JSON schema

### ISSUE THREAD

**Issue by psylector** [raml-org/ramldt2jsonschema#41]
Hi there,

I have 2 simple RAML files and I tried to convert it to JSON schema, but it cause errors.

Used command:
`dt2js definitions.raml Definitions > output-schema.json` (on Mac OS X)

Could you investigate it and help me?

Thanks a milion
Ondrej

[attachment.zip](https://github.com/raml-org/ramldt2jsonschema/files/1831476/attachment.zip)

**Comment by psylector** [comment]
I have one more issue (or maybe question). What is necessary to write in RAML definition to get object type as "oneOf" (object | null) in JSON schema?

See:
[target-schema.json.zip](https://github.com/raml-org/ramldt2jsonschema/files/1831497/target-schema.json.zip)

**Comment by jstoiko** [comment]
@psylector: can you try again using the latest release (v0.1.3 released today)?

> What is necessary to write in RAML definition to get object type as "oneOf" (object | null) in JSON schema?

This is document in the README: ```the JSON schema `oneOf` property is processed the same way as the JSON schema `anyOf` property, it is converted to the RAML `union` type```

**Comment by psylector** [comment]
> can you try again using the latest release (v0.1.3 released today)?

Yes, but the problem still persists.

> This is document in the README: the JSON schema `oneOf` property is processed the same way as the JSON schema `anyOf` property, it is converted to the RAML `union` type

My source object structure will be in RAML and I need to export it to the JSON schema in which we need to have on attributes types 'oneOf x | y' (for some reason).
Is it here some RAML solution, which will ensure object type 'oneOf x | y' in output JSON schema? (like in attached file target-schema.json.zip)

**Comment by psylector** [comment]
I attach you my example of source RAML and expected result oneOf in JSON schema.
[carBrand.raml.zip](https://github.com/raml-org/ramldt2jsonschema/files/1832579/carBrand.raml.zip)

**Comment by jstoiko** [comment]
@psylector: apologies for the delayed answer.

Your RAML is invalid. You `CarBrand` cannot have both `type: nil` and have `properties` defined, even in a union. What you can do to overcome this is to use some sort of intermediary type, see:
```raml
#%RAML 1.0
title: Cars definitions & API
version: 1.1
mediaType: application/json

types:
  CarCodeList:
    type: object
    description: parent of code-lists
    properties:
      id: integer
      active: boolean
  CarCodeListExtended:
    type: CarCodeList
    properties:
      carMark: string
  CarBrand:
    type: nil | CarCodeList | CarCodeListExtended
    description: car brand
```

Closing. Feel free to open a new issue if necessary.
