### ISSUE TITLE
including files with "use" does not seem to work

### ISSUE THREAD

**Issue by danielgoergen** [raml-org/ramldt2jsonschema#49]
I get an error if I include files defining types using 

uses:
  ResourceLib: ResourceLib.raml

I get an error stating it does not know a type defined in the second file
Error: could not resolve: ResourceState

**Comment by jstoiko** [comment]
This seems like an issue with your RAML being invalid. Can you share your entire RAML?

**Comment by jstoiko** [comment]
feel free to re-open and provide additional info if the problem persist.
