### ISSUE TITLE
Validate JSON Schema output of dt2js

### ISSUE THREAD

**Issue by jstoiko** [raml-org/ramldt2jsonschema#55]
ajv can validate JSON Schemas so we might as well use it to validate the output to make sure it is valid. Might want to make this optional though.

**Comment by postatum** [comment]
@jstoiko is this issue still relevant after rework using webapi-parser?
We already validate dt2js output while running integration tests. IMO if integration tests pass, we can assume dt2js produces valid json.
I think this step should be performed during development/testing (as it is now) and not in users' projects.

**Comment by jstoiko** [comment]
would it “cost” a lot to add a `—validate` option to dt2js and use AJV to validate? if not, I think it’s worth working on it for a future minor release.

**Comment by postatum** [comment]
> would it “cost” a lot to add a `—validate` option to dt2js and use AJV to validate?

It wouldn't.

> if not, I think it’s worth working on it for a future minor release.

Ok

**Comment by postatum** [comment]
@jstoiko should validation only work when using dt2js as CLI?
I think it should because when using it from js code:
1. Users can validate output json schema by themselves if they want;
2. Output of dt2js would become complicated because then it would have to be either validation report or json schema, and have some flag to show if schema is valid or not.

Or should it work both in CLI and js and throw an error when output schema is invalid, instead of returning a validation report?

**Comment by jstoiko** [comment]
I have an idea. Would you be able to provide two simple examples, one showing `dt2js` CLI + output pipes using `ajv-cli` (or any other "standard"/popular JSON Schema validator), and the other one showing how to achieve the same in code. Let's see what it looks like. Maybe we don't need this feature at all as longs as they're easy ways to get to the same result.

**Comment by postatum** [comment]
Below are code examples.
Validating output schema in JS code is pretty simple. Validating using CLI, on the other hand, is complicated. I didn't find any CLI libs to validate json schema other than ajv-cli. It doesn't have support for piping so a complex command has to be constructed to make it work with dt2js.

```js
const r2j = require('ramldt2jsonschema')

const ramlData = `#%RAML 1.0 Library
types:
  Cat:
    type: object
    properties:
      name: string
      color: string`

async function main () {
  const schema = await r2j.dt2js(ramlData, 'Cat')
  schema.required = 123
  const Ajv = require('ajv')
  const ajv = new Ajv({ allErrors: true, schemaId: 'auto' })
  const valid = ajv.validateSchema(schema)
  if (!valid) {
    const errorsText = ajv.errorsText(ajv.errors, { separator: '; ' })
    throw new Error(`Invalid json: ${errorsText}`)
  }
}

main()
```
```sh
$ ajv -d <(dt2js ../test/integration/raml/complex_homeanimal.raml Cat) -s <(curl http://json-schema.org/draft-07/schema#)
```
