### ISSUE TITLE
Silent error parsing included files

### ISSUE THREAD

**Issue by kace91** [raml-org/ramldt2jsonschema#61]
I've found a silent error that is produced when trying to parse a file that !includes other datatypes.

Let's say I have the following library:

```
#%RAML 1.0 Library

types:
  Example: 
    properties:
    foo:
      type: string
    bar: !include ./referencedFile.raml
```

And the referenced file:
```

#%RAML 1.0 DataType
type: array
items: string


```

The result, is, as expected:

```
{
  "foo": {
    "type": "string"
  },
  "bar": {
    "type": "array",
    "items": "string"
  },
  "type": "any",
  "$schema": "http://json-schema.org/draft-06/schema#"
}
```
So far, so good. Now, let's introduce a typo in the referenced file (a missing space between "type" and "array":

```

#%RAML 1.0 DataType
type:array
items: string


```

You would expect an error while parsing, however the result is this:

```
{
  "foo": {
    "type": "string"
  },
  "type": "any",
  "$schema": "http://json-schema.org/draft-06/schema#"
}

```

That is to say, the included file is simply ignored while parsing, with no warning to the fact that the result is missing the bar property.

The error happens because this project uses yaml-ast-parser to generate the AST that is later traversed. If it finds a path to a different file, it calls yaml-ast-parser again to said path and includes the result. However, during this second call there is no check to ensure that the yaml has been correctly parsed. 

I'm creating a PR with a fix, so that an error is thrown to warn the user.

**Comment by postatum** [comment]
Thanks for reporting this issue @kace91. We are soon making a new major release which addressed this issue among others.
