### ISSUE TITLE
losing data in json to raml conversion

### ISSUE THREAD

**Issue by ahager98** [raml-org/ramldt2jsonschema#63]
I have a very large json schema I am trying to convert to raml and am seeing far less data than I should in the output file.  Attached is my json schema.

[UpdateReservationRQ.txt](https://github.com/raml-org/ramldt2jsonschema/files/2121301/UpdateReservationRQ.txt)

**Comment by ForsakenHarmony** [comment]
Could you provide more info on what exactly you're missing?

**Comment by jstoiko** [comment]
@ahager98: assuming you may have solved this. feel free to re-open this issue if that's not the case.
