### ISSUE TITLE
dt2js Error: could not resolve: Plan_CodeExtGroup

### ISSUE THREAD

**Issue by bigmule** [raml-org/ramldt2jsonschema#64]
The type I

**Comment by bigmule** [comment]
try to run the following: dt2js common-types.raml PaymentCard
/usr/local/lib/node_modules/ramldt2jsonschema/node_modules/datatype-expansion/src/expanded.js:134
    throw new Error('could not resolve: ' + form)
    ^

Error: could not resolve: Plan_CodeExtGroup 
The common-types.raml contains the following:
uses:
  simpleTypes: simple-types.raml
  lists: lists.raml

Plan_CodeExtGroup is located in lists.raml
Any suggestion of how to resolve the above problem?
Thanks
Juan

**Comment by jstoiko** [comment]
I can try to reproduce but can you share your RAML?

**Comment by bigmule** [comment]
Hi,
Did you received the files?
Regards,
Juan

**Comment by jstoiko** [comment]
nope. you can share them on https://gist.github.com

**Comment by bigmule** [comment]
Here is the command:
dt2js common-types.raml PaymentCard
and here is the error:
/usr/local/lib/node_modules/ramldt2jsonschema/node_modules/datatype-expansion/src/expanded.js:134
 throw new Error('could not resolve: ' + form)
Error: could not resolve: OTA_CodeExtGroup




[raml-files.zip](https://github.com/raml-org/ramldt2jsonschema/files/2202642/raml-files.zip)
The OTA_CodeExtGroup is in lists.raml

**Comment by postatum** [comment]
We are soon releasing new major version which should address this issue among others.
Thanks for reporting it @bigmule !
