### ISSUE TITLE
OAGIS  JSON Schema DRAFT 4 is not converting to RAML 1.0

### ISSUE THREAD

**Issue by dubnemo** [raml-org/ramldt2jsonschema#73]
The attached JSON Schema DRAFT 4 is not converting to RAML 1.0.  It does use additionalProperties keyword, which I thought would not be converted.  This is the output of js2dt which was generated from NIST's Semantic Refinement Tool:

js2dt Purchase-Order-oagis-id-dd32f9c6c01048a19e15c423c9c741ae.json Purchase-Order-oagis-id-dd32f9c6c01048a19e15c423c9c741ae.raml
#%RAML 1.0 Library
types:
  Token: string
  NormalizedString: string
  String: string
  Decimal: number
  Integer: number
  Xbt_BooleanType: boolean
  Purchase-Order-oagis-id-dd32f9c6c01048a19e15c423c9c741ae.raml:
    type: object
    properties:
      purchaseOrder: array
    additionalProperties: false

Stops there, NO raml file is created.

[Purchase-Order-oagis-id-dd32f9c6c01048a19e15c423c9c741ae.json.txt](https://github.com/raml-org/ramldt2jsonschema/files/2503284/Purchase-Order-oagis-id-dd32f9c6c01048a19e15c423c9c741ae.json.txt)

**Comment by jstoiko** [comment]
This tool does not create files per sé but you can pipe the content to one, e.g. `$ js2dt Foo.json Foo > Foo.raml`

**Comment by jstoiko** [comment]
I see what the problem is. The latest version of `ramldt2jsonschema` only supports JSON Schema DRAFT 6. You can still use an older version though.

```sh
$ npm i ramldt2jsonschema@0.1.5
```

I've tested it with 0.1.5 and it works so I'll close this issue for now.
