### ISSUE TITLE
Enum is supported in dt2js but not js2dt

### ISSUE THREAD

**Issue by Chudesnov** [raml-org/ramldt2jsonschema#77]
This works:

test/examples/type_conversion_test.raml:
```raml
types:
  TimeRange:
    type: string
    enum:
      - "1"
      - "30"
```

npx ramldt2jsonschema test/examples/type_conversion_test.raml TimeRange
```json
{
  "type": "string",
  "enum": [
    "1",
    "30"
  ],
  "$schema": "http://json-schema.org/draft-06/schema#"
}
```

This does not:

test/examples/type_conversion_test.json:
```json
{
  "type": "string",
  "enum": [
    "1",
    "30"
  ],
  "$schema": "http://json-schema.org/draft-06/schema#"
}
```
npx --package ramldt2jsonschema js2dt test/examples/type_conversion_test.json TimeRange

```raml
#%RAML 1.0 Library
types:
  TimeRange:
    type: string
```

**Comment by postatum** [comment]
Thanks for reporting this issue @Chudesnov.

We are soon releasing a new major version which supports enums.
