### ISSUE TITLE
js2dt: invalid conversion for array

### ISSUE THREAD

**Issue by rakeshjain0512** [raml-org/ramldt2jsonschema#81]
If generated json schema contains array then js2dt script does not generate expected raml datatype contains. Below is the sample json.
`
{
  "type":"array",
  "items" : {
    "type" : "object",
    "properties": {
      "foo": {
        "type": "string"
      },
      "bar": {
        "type": "integer"
      },
      "baz": {
        "type": "boolean"
      }
    }
  }
}
`

After running js2dt I get the output as below.

`
#%RAML 1.0 DataType
type: array

`

It is not including any of the properties of array object.

**Comment by sophieze** [comment]
I added a PR to fix this #88

**Comment by postatum** [comment]
Hi @rakeshjain0512. Thanks for reporting this issue!

We are soon releasing new major version which addresses this issue among others.
