### ISSUE TITLE
Use webapi-parser to convert

### ISSUE THREAD

**Issue by jstoiko** [raml-org/ramldt2jsonschema#90]
[`webapi-parser`](https://github.com/raml-org/webapi-parser) new official RAML parser has a mechanism to go from [JSON Schema to RAML DataType](https://raml-org.github.io/webapi-parser/translating-json-raml.html) and [vice-versa](https://raml-org.github.io/webapi-parser/translating-raml-json.html).

We should either consider deprecating this tool or replacing its underlying translation logic with the one bundled with `webapi-parser`.

**Comment by postatum** [comment]
- [x] return output of webapi-parser
  - [x] dt2js
  - [x] dt2js cli
  - [x] js2dt
  - [x] js2dt cli
- [x] remove x-amf- properties by hand
- [x] check bins
- [x] remove not used deps
- [x] clean up the code
- [ ] update examples
- [ ] test by hand
  - [ ] dt2js example
  - [ ] dt2js cli
  - [ ] dt2js bin
  - [ ] js2dt example
  - [ ] js2dt cli
  - [ ] js2dt bin
- [ ] fix tests
- [ ] update readme

**Comment by postatum** [comment]
Blocked by https://github.com/raml-org/webapi-parser/pull/30

**Comment by postatum** [comment]
TODO:
- [ ] Add `basePath` support back (waiting for https://github.com/raml-org/webapi-parser/pull/37 to be approved)
