### ISSUE TITLE
Schema generation not working properly when raml key contains dot('.') in it 

### ISSUE THREAD

**Issue by Abn02** [raml-org/ramldt2jsonschema#98]
https://github.com/raml-org/ramldt2jsonschema/blob/master/src/dt2js.js 
in this file under traverse method joining keys with '.' which is causing the issue. It is working if i change delimiter.

**Comment by postatum** [comment]
Hi @Abn02.
We are soon releasing a new major version which addresses this issue. Thanks for reporting it!

**Comment by anjidevarasetty** [comment]
Hi @postatum Thanks for the update
please update once new version released.

**Comment by postatum** [comment]
Hi @anjidevarasetty. It has been released. The new version is 1.0.0.
